repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
    - id: detect-private-key
      exclude: |
        (?x)^(
            lambdas/drivingpermitcheck/src/test/java/uk/gov/di/ipv/cri/drivingpermit/api/service/ThirdPartyAPIServiceFactoryTest.java|
            scripts/load-crypto-params-for-non-ca-env-non-prod.sh|
            lib-dva/src/test/java/uk/gov/di/ipv/cri/drivingpermit/library/dva/service/DVACloseableHttpClientFactoryTest.java
        )$

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v1.18.1 # The version of cfn-lint to use
    hooks:
    - id: cfn-python-lint
      files: .template\.yaml$

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.456'
    hooks:
    - id: checkov
      verbose: true
      args: [--soft-fail]
      files: \.y(a)?ml$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ["--baseline", ".secrets.baseline"]
