plugins {
	alias(libs.plugins.idea)
	alias(libs.plugins.java)
	alias(libs.plugins.jacoco)
}

dependencies {
	aspect libs.powertools.metrics,
			libs.powertools.logging

	implementation libs.aspectjrt,
			libs.powertools.logging.log4j,
			project(":lib"),
			libs.limeade,
			libs.cri.common.lib,
			libs.aws.sdk.lambda,
			libs.aws.sdk.dynamodb.enhanced,
			libs.aws.sdk.kms,
			libs.aws.sdk.sqs,
			libs.aws.sdk.crt.client,
			libs.aws.lambda.java.core,
			libs.aws.lambda.java.events,
			libs.bundles.jackson,
			libs.opentelemetry.aws.sdk,
			libs.nimbus.oauth

	testImplementation testFixtures(project(":lib")),
			libs.bundles.pact

	constraints {
		// TODO: remove this forced version of bouncycastle when the pact provider is updated
		def reason = 'override vulnerable bouncycastle version present in pact provider to 1.86'
		testImplementation(libs.bouncycastle.bcprov) {
			because reason
		}
		testImplementation(libs.bouncycastle.bcpkix) {
			because reason
		}
		testImplementation(libs.bouncycastle.bcutil) {
			because reason
		}
	}
}
