plugins {
	alias(libs.plugins.idea)
	alias(libs.plugins.java.library)
	alias(libs.plugins.java.test.fixtures)
	alias(libs.plugins.jacoco)
}

dependencies {
	implementation libs.aspectjrt,
			libs.powertools.logging.log4j,
			libs.powertools.metrics,
			project(":lib"),
			libs.limeade,
			libs.cri.common.lib,
			libs.aws.sdk.kms,
			libs.aws.sdk.acm,
			libs.bundles.jackson,
			libs.nimbus.oauth,
			libs.bouncycastle.bcpkix,
			libs.apache.httpcomponents.httpcore,
			libs.apache.httpcomponents.httpclient

	testImplementation testFixtures(project(":lib"))

	testFixturesImplementation testFixtures(project(":lib")),
			libs.aspectjrt
}
