name: Clean up stale preview deployments
run-name: Delete stale preview deployments

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am (9am is used by pre-merge-cleanup - deletion rate limits)
    - cron: "0 10 * * 1-5"

permissions:
  id-token: write
  contents: read

concurrency: cleanup-dev-${{ github.head_ref || github.ref_name }}

jobs:
  delete-stacks:
    name: Delete stale stacks
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497
        with:
          role-to-assume: ${{ secrets.AWS_DL_DEV_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Get stale preview stacks
        uses: govuk-one-login/github-actions/sam/get-stale-stacks@a531d6d1728c39ebc292abf2cf1738d4e43ebd44
        with:
          threshold-days: 14
          stack-name-filter: preview-ipv-cri-dl-api
          stack-tag-filters: |
            cri:deployment-source=github-actions
            cri:stack-type=preview
          description: preview
          env-var-name: STACKS

      - name: Delete stacks
        if: ${{ env.STACKS != null }}
        uses: govuk-one-login/github-actions/sam/delete-stacks@a531d6d1728c39ebc292abf2cf1738d4e43ebd44
        with:
          stack-names: ${{ env.STACKS }}
          verbose: true
