name: Clean up stale pre-merge deployments
run-name: Delete stale pre-merge deployments

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 9am (10am is used by preview-cleanup - deletion rate limits)
    - cron: "0 9 * * 1-5"

permissions:
  id-token: write
  contents: read

concurrency: cleanup-dev-${{ github.head_ref || github.ref_name }}

jobs:
  delete-stacks:
    name: Delete stale stacks
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DL_DEV_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Get stale pre-merge stacks
        uses: govuk-one-login/github-actions/sam/get-stale-stacks@main
        with:
          threshold-days: 1 # Pre-merge are short-lived test stacks
          stack-name-filter: pre-merge
          stack-tag-filters: |
            cri:component=ipv-cri-dl-api
            cri:stack-type=pre-merge
            cri:application=Lime
            cri:deployment-source=github-actions
          env-var-name: STACKS

      - name: Delete stacks
        if: ${{ env.STACKS != null }}
        uses: govuk-one-login/github-actions/sam/delete-stacks@main
        with:
          stack-names: ${{ env.STACKS }}
          verbose: true
