name: Package ACM for Build
on:
  push:
    branches:
      - main
  workflow_dispatch: # deploy manually

jobs:
  deploy:
    name: Package ACM for build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          version: "1.134.0"

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.BUILD_DL_ACM_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/certificate/template.yaml

      - name: SAM build
        run: |
          mkdir build
          sam build -t infrastructure/certificate/template.yaml -b out


      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.9
        with:
          artifact-bucket-name: "${{ secrets.BUILD_DL_ACM_ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.SIGNING_PROFILE_NAME }}"
          working-directory: ./out
