name: Deploy ACM to dev
on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/certificate/template.yaml"
      - ".github/workflows/post-merge-deploy-acm-to-dev.yml"

  workflow_dispatch: # deploy manually

jobs:
  deploy:
    name: Deploy to acm dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      STACK_NAME: acm-infrastructure-pipeline
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup SAM
        uses: aws-actions/setup-sam@f664fad9e12492edfc187a31f575537dfbb0ff63
        with:
          use-installer: true
          version: "1.134.0"

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497
        with:
          role-to-assume: ${{ secrets.DEV_DL_ACM_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/certificate/template.yaml

      - name: SAM build
        run: |
          mkdir out
          sam build -t infrastructure/certificate/template.yaml -b out

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@dc8158079d3976d613515180e543930cdbe73f5f
        with:
          artifact-bucket-name: "${{ secrets.DEV_DL_ACM_ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.DEV_SIGNING_PROFILE_NAME }}"
          working-directory: ./out
