name: Package for Build
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy:
    name: Package for build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version-file: '.sdkmanrc'
          distribution: corretto
          cache: gradle

      - uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Setup SAM
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true
          version: "1.157.1"

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: "v3.0.5"

      - name: Create shared signing config
        run: cosign signing-config create --with-default-services=true --no-default-rekor=true --out signing.config

      - name: Build, tag, and push traffic test image to ECR
        env:
          CONTAINER_SIGN_KMS_KEY: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_TRAFFIC_BUILD: ${{ secrets.ECR_REPOSITORY_TRAFFIC_BUILD }}
          IMAGE_TAG: latest
          DOCKER_TARGET: traffic_test_image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_TRAFFIC_BUILD:$IMAGE_TAG -f acceptance-tests/Dockerfile --target $DOCKER_TARGET .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_TRAFFIC_BUILD:$IMAGE_TAG
          cosign sign --yes --signing-config signing.config --key awskms:///${CONTAINER_SIGN_KMS_KEY} $ECR_REGISTRY/$ECR_REPOSITORY_TRAFFIC_BUILD:$IMAGE_TAG

      - name: Build, tag, and push testing images to Amazon ECR
        env:
          CONTAINER_SIGN_KMS_KEY: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_BUILD: ${{ secrets.ECR_REPOSITORY_BUILD }}
          ECR_REPOSITORY_STAGING: ${{ secrets.ECR_REPOSITORY_STAGING }}
          IMAGE_TAG: latest
          DOCKER_TARGET: ac_test_image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BUILD:$IMAGE_TAG -f acceptance-tests/Dockerfile --target $DOCKER_TARGET .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BUILD:$IMAGE_TAG
          cosign sign --yes --signing-config signing.config --key awskms:///${CONTAINER_SIGN_KMS_KEY} $ECR_REGISTRY/$ECR_REPOSITORY_BUILD:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY_BUILD:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_STAGING:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_STAGING:$IMAGE_TAG
          cosign sign --yes --signing-config signing.config --key awskms:///${CONTAINER_SIGN_KMS_KEY} $ECR_REGISTRY/$ECR_REPOSITORY_STAGING:$IMAGE_TAG

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/lambda/template.yaml --lint

      - name: SAM build
        run: |
          mkdir out
          chmod a+x gradlew
          sam build -s "${GITHUB_WORKSPACE}" -t infrastructure/lambda/template.yaml -b out

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf # v4.1.0
        with:
          artifact-bucket-name: "${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.SIGNING_PROFILE_NAME }}"
          working-directory: ./out
