name: Package ACM for Build
on:
  push:
    branches:
      - main
  workflow_dispatch: # deploy manually

permissions: {}

jobs:
  deploy:
    name: Package ACM for build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup SAM
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310 # v3
        with:
          use-installer: true
          version: "1.157.1"

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.BUILD_DL_ACM_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/certificate/template.yaml

      - name: SAM build
        run: |
          mkdir build
          sam build -t infrastructure/certificate/template.yaml -b out

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf # v4.1.0
        with:
          artifact-bucket-name: "${{ secrets.BUILD_DL_ACM_ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.SIGNING_PROFILE_NAME }}"
          working-directory: ./out
