name: Package ACM for Build
on:
  push:
    branches:
      - main
  workflow_dispatch: # deploy manually

permissions: {}

jobs:
  deploy:
    name: Package ACM for build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup SAM
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true
          version: "1.157.1"

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.BUILD_DL_ACM_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/certificate/template.yaml

      - name: SAM build
        run: |
          mkdir build
          sam build -t infrastructure/certificate/template.yaml -b out

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1 # v3.14.0
        with:
          artifact-bucket-name: "${{ secrets.BUILD_DL_ACM_ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.SIGNING_PROFILE_NAME }}"
          working-directory: ./out
