name: Java build check

on:
  workflow_call:

concurrency:
  group: java-build-check-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  java-build-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version-file: '.sdkmanrc'
          distribution: corretto
          cache: gradle

      - uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Build Cache
        uses: actions/cache@v5
        with:
          path: |
            .gradle/
            */build/
            */**/build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run Build
        run: ./gradlew --parallel build -x test -x spotlessApply -x spotlessCheck && AC_TEST_ONLY=true ./gradlew --parallel build -x test -x spotlessApply -x spotlessCheck
