name: Pact tests

on:
  workflow_call:
    secrets:
      PACT_BROKER_HOST: { required: true }
      PACT_BROKER_USERNAME: { required: true }
      PACT_BROKER_PASSWORD: { required: true }

concurrency:
  group: pact-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  run-pact-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version-file: '.sdkmanrc'
          distribution: corretto
          cache: gradle

      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Build Cache
        uses: actions/cache@v5
        with:
          path: |
            .gradle/
            */build/
            */**/build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run pact tests
        env:
          PACT_BROKER_HOST: ${{ inputs.PACT_BROKER_HOST || secrets.PACT_BROKER_HOST }}
          PACT_BROKER_USERNAME: ${{ inputs.PACT_BROKER_USERNAME || secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ inputs.PACT_BROKER_PASSWORD || secrets.PACT_BROKER_PASSWORD }}
        run: ./gradlew pactTests -x spotlessApply -x spotlessCheck
