name: Infra tests

on:
  workflow_call:
    inputs:
      coverage-report: { type: boolean, required: false, default: false }
      coverage-artifact: { type: string, required: false, default: coverage }
    outputs:
      coverage-artifact:
        value: ${{ inputs.coverage-artifact }}

concurrency:
  group: infra-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  infra-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version-file: '.sdkmanrc'
          distribution: corretto
          cache: gradle

      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Build Cache
        uses: actions/cache@v5
        with:
          path: |
            .gradle/
            */build/
            */**/build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run Infra Tests
        run: AC_TEST_ONLY=true ./gradlew :acceptance-tests:infra-test -x spotlessApply -x spotlessCheck
